sudo: false
jdk: oraclejdk8
language: scala

scala:
   - 2.11.12
matrix:
   include:
      - env: PLAY_VERSION=2.3.10
        scala: 2.11.12

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues
