version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: mysql:5.5
        command: |
        mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
        mysqld -e "CREATE USER 'ubuntu'@'localhost' IDENTIFIED BY 'ubuntu';GRANT ALL on *.* TO 'ubuntu'@'localhost' IDENTIFIED BY 'ubuntu' WITH GRANT OPTION;FLUSH PRIVILEGES;"
        mysqld -e "CREATE DATABASE test_play;"
        # CHANGE DEFAULT MYSQL ENVIRONMENT!
        environment:
         MYSQL_USER: root
         MYSQL_ROOT_PASSWORD: ubuntu
         MYSQL_DATABASE: odenktools_play
    working_directory: ~/playframework-sakila
    branches:
      only:
        - master
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: sudo apt-get install pv
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: cp ~/playframework-sakila/conf/application.ci.txt ~/playframework-sakila/conf/application.conf
      - save_cache:
          paths:
            - ~/.m2
            - "~/.sbt"
            - "target/resolution-cache"
            - "target/streams"
            - "project/target/resolution-cache"
            - "project/target/streams"
          key: v1-dependencies--{{ checksum "build.sbt" }}             
      - run: sudo chmod +x db-import.sh
      - run: ./db-import.sh
      # run tests!
      - run: cat /dev/null | sbt test:test
