version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: mysql:5.5
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
        environment:
         MYSQL_USER: root
         MYSQL_ROOT_PASSWORD: ubuntu
         MYSQL_DATABASE: odenktools_play
    working_directory: ~/playframework-sakila
    branches:
      only:
        - master
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: sudo apt-get install pv
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          - v1-dependencies-
      - run: cp conf/application.ci.txt conf/application.conf
      - run: cat conf/application.conf
      - save_cache:
          paths:
            - ~/.m2
            - "~/.sbt"
            - "target/resolution-cache"
            - "target/streams"
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - run: cat /dev/null | sbt test:test